# Python Libraries and Data Science

In [1]:
import numpy as np

li = [1,2,3]
a = np.array(li)
a

array([1, 2, 3])

In [2]:
# Genetarin the elements 
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Generating random integers
rn = np.random.randint(0,20,size = 10)
rn

array([11, 16,  0,  1, 12,  0,  7,  4,  5, 10])

In [4]:
# Generate 2D Matrix
rn = np.random.randint(0,2,size = (2,2))
rn

array([[0, 0],
       [0, 0]])

In [5]:
# generating 3D Matrix
rn = np.random.randint(0,2,size = (3,3,3,3))
rn

array([[[[0, 1, 1],
         [0, 0, 0],
         [0, 1, 0]],

        [[1, 0, 1],
         [0, 0, 1],
         [0, 1, 1]],

        [[0, 1, 0],
         [1, 1, 0],
         [0, 0, 1]]],


       [[[0, 0, 1],
         [0, 1, 1],
         [1, 0, 0]],

        [[1, 1, 1],
         [0, 1, 0],
         [1, 1, 1]],

        [[1, 0, 1],
         [0, 0, 0],
         [1, 1, 0]]],


       [[[1, 0, 1],
         [0, 0, 1],
         [1, 1, 1]],

        [[0, 1, 1],
         [0, 1, 0],
         [0, 0, 0]],

        [[1, 1, 0],
         [1, 0, 0],
         [1, 1, 1]]]])

In [6]:
print(rn.ndim) # Dimension
print(rn.size) # Size
print(rn.shape) # Shape
print(rn.dtype) #
print(rn.itemsize) #
print(rn.nbytes) # total capacity of the array

4
81
(3, 3, 3, 3)
int32
4
324


In [7]:
# Indexing of arrays starts with 0
rn[0]

array([[[0, 1, 1],
        [0, 0, 0],
        [0, 1, 0]],

       [[1, 0, 1],
        [0, 0, 1],
        [0, 1, 1]],

       [[0, 1, 0],
        [1, 1, 0],
        [0, 0, 1]]])

In [8]:
rn[0,0] = 123

In [9]:
rn[:2,:3]

array([[[[123, 123, 123],
         [123, 123, 123],
         [123, 123, 123]],

        [[  1,   0,   1],
         [  0,   0,   1],
         [  0,   1,   1]],

        [[  0,   1,   0],
         [  1,   1,   0],
         [  0,   0,   1]]],


       [[[  0,   0,   1],
         [  0,   1,   1],
         [  1,   0,   0]],

        [[  1,   1,   1],
         [  0,   1,   0],
         [  1,   1,   1]],

        [[  1,   0,   1],
         [  0,   0,   0],
         [  1,   1,   0]]]])

In [13]:
# Reshape the array
b = np.arange(15)
print(b)
b.reshape(5,3)# 5 is rows and 3 is columns

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
# Time it
import timeit
st = timeit.default_timer()
#jdsklfjsk
print(timeit.default_timer()-st)


In [ ]:
# UnVenctorized 

# Panda's
- Use cases:
    - Data Cleaning
    - Data Transformation
    - Data Analysis
- Notations:
    - Series
    - Data Frames

In [35]:
import pandas as pd

internal_1 = {'s1':21,'s2':18,'s3':24}
internal_2 = {'s1':15,'s2':18,'s3':20}

internal_1 = pd.Series(internal_1)
internal_2 = pd.Series(internal_2)
internal_2
avg = pd.Series((internal_1+internal_2)/2)
avg

s1    18.0
s2    18.0
s3    22.0
dtype: float64

In [36]:
final = {'Internal-1':internal_1,'Internal-2':internal_2,'Average':avg}
final = pd.DataFrame(final)
final

Internal-1  Internal-2  Average
s1          21          15     18.0
s2          18          18     18.0
s3          24          20     22.0

In [37]:
final.columns # Columns names

Index(['Internal-1', 'Internal-2', 'Average'], dtype='object')

In [38]:
final.values # Valuesjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj

array([[21., 15., 18.],
       [18., 18., 18.],
       [24., 20., 22.]])

In [39]:
final.values[2,0]

24.0

In [40]:
for row in final.values:
    print('Internal-1:',row[0],'Internal-2:',row[1])

Internal-1: 21.0 Internal-2: 15.0
Internal-1: 18.0 Internal-2: 18.0
Internal-1: 24.0 Internal-2: 20.0


In [41]:
final

Internal-1  Internal-2  Average
s1          21          15     18.0
s2          18          18     18.0
s3          24          20     22.0

In [46]:
final.loc['s3'] = [10,10,10]
final

Internal-1  Internal-2  Average
s1          21          15     18.0
s2          18          18     18.0
s3          10          10     10.0

In [47]:
final.values[2] = [25,25,25]

In [48]:
final


Internal-1  Internal-2  Average
s1          21          15     18.0
s2          18          18     18.0
s3          10          10     10.0

In [52]:
# Read CSV file Data
import pandas as pd
filepath = 'DataFiles/income.csv'
income_df = pd.read_csv(filepath)
income_df

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [60]:
# Extract income of all states in 2013
income_df.values

array([['04000US01', 'Alabama', 37150, 37952, 42212, 44476, 39980, 40933,
        42590, 43464, 41381],
       ['04000US02', 'Alaska', 55891, 56418, 62993, 63989, 61604, 57848,
        57431, 63648, 61137],
       ['04000US04', 'Arizona', 45245, 46657, 47215, 46914, 45739, 46896,
        48621, 47044, 50602],
       ['04000US05', 'Arkansas', 36658, 37057, 40795, 39586, 36538,
        38587, 41302, 39018, 39919],
       ['04000US06', 'California', 51755, 55319, 55734, 57014, 56134,
        54283, 53367, 57020, 57528]], dtype=object)

In [58]:
for row in income_df.values:
    print(row[1],':',row[-1])
len(income_df.values)

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


5

In [57]:
# Avg income of arizona
su = 0
for row in range(2,11):
    su+=income_df.values[2][row]
print(su/9) # length income_df.values[2][2:]

47214.77777777778


In [65]:
# Avg of 2012

s = 0
for row in income_df.values:
    s += int(row[-2])
s/len(income_df.values)
    

50038.8